# Set Variables

Set maximum number of individuals filtered per country/outgroup:

In [1]:
max_indiv_per_group = 5

Set mosquito species (or set to `None` if no filtering desired):

In [2]:
mosq_species = "gam"  # possible values: "gam", "col", None
# mosq_species = None

Set variable below to the desired country for filtering:

In [3]:
country = "Ghana"

Set index column:

In [4]:
index_col = "ox_code"

# Get IDs of mosquitoes from West Africa vs outgroup

In [5]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 199)

In [6]:
df = pd.read_csv("samples.meta.txt", sep='\t', index_col=index_col)
df

,src_code,population,country,location,site,contributor,contact,year,m_s,sex,n_sequences,mean_coverage,ebi_sample_acc,latitude,longitude
ox_code,,,,,,,,,,,,,,,
AA0040-C,Twifo_Praso__E2,GHcol,Ghana,Twifo Praso,Twifo Praso,David Weetman,David Weetman,2012,M,F,95033368,30.99,ERS311878,5.60858,-1.54926
AA0041-C,Twifo_Praso__H3,GHcol,Ghana,Twifo Praso,Twifo Praso,David Weetman,David Weetman,2012,M,F,95843804,31.70,ERS311886,5.60858,-1.54926
AA0042-C,Takoradi_C7,GHcol,Ghana,Takoradi,Takoradi,David Weetman,David Weetman,2012,M,F,107420666,35.65,ERS311894,4.91217,-1.77397
AA0043-C,Takoradi_H8,GHcol,Ghana,Takoradi,Takoradi,David Weetman,David Weetman,2012,M,F,95993752,29.46,ERS311902,4.91217,-1.77397
AA0044-C,Takoradi_D10,GHcol,Ghana,Takoradi,Takoradi,David Weetman,David Weetman,2012,M,F,103044262,33.67,ERS311910,4.91217,-1.77397
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AY0087-C,Tia_dPM_46,CIcol,Cote d'Ivoire,Tiassale,Tiassale,David Weetman,David Weetman,2012,M,F,101458232,32.56,ERS311822,5.89839,-4.82293
AY0088-C,Tia_dPM_52,CIcol,Cote d'Ivoire,Tiassale,Tiassale,David Weetman,David Weetman,2012,M,F,95140584,30.75,ERS311830,5.89839,-4.82293
AY0089-C,Tia_aPM_4,CIcol,Cote d'Ivoire,Tiassale,Tiassale,David Weetman,David Weetman,2012,M,F,92383724,29.04,ERS311838,5.89839,-4.82293
AY0090-C,Tia_aPM_13,CIcol,Cote d'Ivoire,Tiassale,Tiassale,David Weetman,David Weetman,2012,M,F,96210618,30.94,ERS311846,5.89839,-4.82293
AY0091-C,Tia_aPM_37,CIcol,Cote d'Ivoire,Tiassale,Tiassale,David Weetman,David Weetman,2012,M,F,95973872,31.30,ERS311854,5.89839,-4.82293

Select only single mosquito species (*Anopheles gambiae*):

In [7]:
populations = list(df["population"].unique())
populations

['GHcol',
 'GHgam',
 'BFgam',
 'BFcol',
 'UGgam',
 'GM',
 'GW',
 'KE',
 'CMgam',
 'FRgam',
 'GQgam',
 'AOcol',
 'GAgam',
 'GNgam',
 'GNcol',
 'CIcol']

In [8]:
if mosq_species:
    selection_mask = df["population"].str.contains(mosq_species)
    df = df[selection_mask]
df

,src_code,population,country,location,site,contributor,contact,year,m_s,sex,n_sequences,mean_coverage,ebi_sample_acc,latitude,longitude
ox_code,,,,,,,,,,,,,,,
AA0048-C,Madina_A1,GHgam,Ghana,Madina,Madina,David Weetman,David Weetman,2012,S,F,101183648,32.64,ERS311942,5.66849,-0.21928
AA0050-C,Madina_E5,GHgam,Ghana,Madina,Madina,David Weetman,David Weetman,2012,S,F,93961924,29.82,ERS311958,5.66849,-0.21928
AA0060-C,Madina_C1,GHgam,Ghana,Madina,Madina,David Weetman,David Weetman,2012,S,F,90534918,29.46,ERS311943,5.66849,-0.21928
AA0061-C,Madina_F3,GHgam,Ghana,Madina,Madina,David Weetman,David Weetman,2012,S,F,91137592,29.45,ERS311951,5.66849,-0.21928
AA0072-C,Madina_F1,GHgam,Ghana,Madina,Madina,David Weetman,David Weetman,2012,S,F,97192268,29.31,ERS311944,5.66849,-0.21928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AV0041-C,KD264,GNgam,Guinea,Koundara,Koundara,Kenneth Vernick,"Michelle Riehle, Karin Eiglmeier",2012,S,F,83840132,25.99,ERS224855,8.50000,-9.41700
AV0043-C,KD306,GNgam,Guinea,Koundara,Koundara,Kenneth Vernick,"Michelle Riehle, Karin Eiglmeier",2012,S,F,36846414,12.06,ERS224427,8.50000,-9.41700
AV0044-C,KD309,GNgam,Guinea,Koundara,Koundara,Kenneth Vernick,"Michelle Riehle, Karin Eiglmeier",2012,S,F,108387868,31.85,ERS224653,8.50000,-9.41700
AV0045-C,KD339,GNgam,Guinea,Koundara,Koundara,Kenneth Vernick,"Michelle Riehle, Karin Eiglmeier",2012,S,F,98115760,30.80,ERS224861,8.50000,-9.41700
AV0047-C,KD363,GNgam,Guinea,Koundara,Koundara,Kenneth Vernick,"Michelle Riehle, Karin Eiglmeier",2012,S,F,103391134,30.94,ERS224657,8.50000,-9.41700

In [9]:
selected_populations = list(df["population"].unique())
selected_populations

['GHgam', 'BFgam', 'UGgam', 'CMgam', 'FRgam', 'GQgam', 'GAgam', 'GNgam']

In [10]:
countries = list(df["country"].unique())
countries

['Ghana',
 'Burkina Faso',
 'Uganda',
 'Cameroon',
 'France',
 'Equatorial Guinea',
 'Gabon',
 'Guinea']

From https://en.wikipedia.org/wiki/West_Africa \[accessed on May 1, 2020\]

> The United Nations defines Western Africa as the 16 countries of Benin, Burkina Faso, Cape Verde, The Gambia, Ghana, Guinea, Guinea-Bissau, Ivory Coast, Liberia, Mali, Mauritania, Niger, Nigeria, Senegal, Sierra Leone and Togo, as well as the United Kingdom Overseas Territory of Saint Helena, Ascension and Tristan da Cunha

In [11]:
west_afr = ["Benin", "Burkina Faso", "Cape Verde", "Gambia, The", "Ghana", "Guinea", "Guinea-Bissau", "Cote d'Ivoire", "Liberia", "Mali", "Mauritania", "Niger", "Nigeria", "Senegal", "Sierra Leone", "Togo", "the United Kingdom Overseas Territory of Saint Helena, Ascension and Tristan da Cunha"]
west_countries = [country for country in countries if country in west_afr]
outgroup = [country for country in countries if country not in west_afr]

# print(type(west_afr))
# print(type(countries))
# print(type(west_countries))
# print(type(outgroup))

print(f"west_afr == {west_afr}\n")
print(f"countries == {countries}\n")
print(f"west_countries == {west_countries}\n")
print(f"outgroup == {outgroup}")

west_afr == ['Benin', 'Burkina Faso', 'Cape Verde', 'Gambia, The', 'Ghana', 'Guinea', 'Guinea-Bissau', "Cote d'Ivoire", 'Liberia', 'Mali', 'Mauritania', 'Niger', 'Nigeria', 'Senegal', 'Sierra Leone', 'Togo', 'the United Kingdom Overseas Territory of Saint Helena, Ascension and Tristan da Cunha']

countries == ['Ghana', 'Burkina Faso', 'Uganda', 'Cameroon', 'France', 'Equatorial Guinea', 'Gabon', 'Guinea']

west_countries == ['Ghana', 'Burkina Faso', 'Guinea']

outgroup == ['Uganda', 'Cameroon', 'France', 'Equatorial Guinea', 'Gabon']

Histogram of West African countries and the outgroup:

In [12]:
histogram = {}
def update_histogram(key):
    if key not in histogram.keys():
        histogram[key] = 1
    else:
        histogram[key] += 1

for _, row in df.iterrows():

    if row["country"] in west_countries:
        update_histogram(row["country"])
    if row["country"] in outgroup:        
        update_histogram("outgroup")
    
print(f"histogram == {histogram}")

histogram == {'Ghana': 12, 'Burkina Faso': 92, 'outgroup': 511, 'Guinea': 40}

In [13]:
# check total counts
total_individuals = len(df.index)
print(f"total_individuals == {total_individuals}")

hist_sum = 0
for val in histogram.values():
    hist_sum += val
print(f"hist_sum == {hist_sum} ")

total_individuals == 655
hist_sum == 655

In [14]:
np_mask = np.array([False] * total_individuals)
# print(f"np_mask == {np_mask}, np_mask.shape == {np_mask.shape}\n")

histogram = {}       
for i, (_, row) in enumerate(df.iterrows()):
    hist_key = None
    if row["country"] in west_countries:
        hist_key = row["country"]
    elif row["country"] in outgroup:        
        hist_key = "outgroup"
        
    if hist_key:
        update_histogram(hist_key)
        if histogram[hist_key] <= max_indiv_per_group:
            np_mask[i] = True
    
print(f"histogram == {histogram}")

n_selected = np.sum(np_mask)
assert n_selected == len(histogram.keys()) * max_indiv_per_group
print(f"n_selected ({n_selected}) == "
      f"{len(histogram.keys())} * {max_indiv_per_group} == "
      f"({len(histogram.keys()) * max_indiv_per_group})")

histogram == {'Ghana': 12, 'Burkina Faso': 92, 'outgroup': 511, 'Guinea': 40}
n_selected (20) == 4 * 5 == (20)

In [15]:
# select mosquitoes
df_west_and_outgroup = df[np_mask]
assert len(df_west_and_outgroup.index) == n_selected
df_west_and_outgroup

,src_code,population,country,location,site,contributor,contact,year,m_s,sex,n_sequences,mean_coverage,ebi_sample_acc,latitude,longitude
ox_code,,,,,,,,,,,,,,,
AA0048-C,Madina_A1,GHgam,Ghana,Madina,Madina,David Weetman,David Weetman,2012,S,F,101183648,32.64,ERS311942,5.66849,-0.21928
AA0050-C,Madina_E5,GHgam,Ghana,Madina,Madina,David Weetman,David Weetman,2012,S,F,93961924,29.82,ERS311958,5.66849,-0.21928
AA0060-C,Madina_C1,GHgam,Ghana,Madina,Madina,David Weetman,David Weetman,2012,S,F,90534918,29.46,ERS311943,5.66849,-0.21928
AA0061-C,Madina_F3,GHgam,Ghana,Madina,Madina,David Weetman,David Weetman,2012,S,F,91137592,29.45,ERS311951,5.66849,-0.21928
AA0072-C,Madina_F1,GHgam,Ghana,Madina,Madina,David Weetman,David Weetman,2012,S,F,97192268,29.31,ERS311944,5.66849,-0.21928
AB0085-C,BF2-4,BFgam,Burkina Faso,Pala,Pala,Austin Burt,Sam O'Loughlin,2012,S,F,89905852,28.01,ERS223996,11.15000,-4.23500
AB0103-C,BF6-7,BFgam,Burkina Faso,Bana,Bana,Austin Burt,Sam O'Loughlin,2012,S,F,105747410,31.85,ERS223970,11.23300,-4.47200
AB0104-C,BF6-8,BFgam,Burkina Faso,Bana,Bana,Austin Burt,Sam O'Loughlin,2012,S,F,110651954,33.23,ERS223976,11.23300,-4.47200
AB0108-C,BF7-5,BFgam,Burkina Faso,Pala,Pala,Austin Burt,Sam O'Loughlin,2012,S,F,111394400,12.01,ERS223919,11.15000,-4.23500
AB0117-C,BF3-21,BFgam,Burkina Faso,Bana,Bana,Austin Burt,Sam O'Loughlin,2012,S,M,78682840,24.30,ERS224010,11.23300,-4.47200
AC0089-C,1_A1,UGgam,Uganda,Tororo,Nagongera,Martin Donnelly,Craig Wilding,2012,S,F,94035400,30.28,ERS223947,0.77000,34.02600
AC0090-C,1_A4,UGgam,Uganda,Tororo,Nagongera,Martin Donnelly,Craig Wilding,2012,S,F,109522970,34.43,ERS223917,0.77000,34.02600
AC0091-C,1_A5,UGgam,Uganda,Tororo,Nagongera,Martin Donnelly,Craig Wilding,2012,S,F,86481608,27.27,ERS224027,0.77000,34.02600
AC0092-C,1_A8,UGgam,Uganda,Tororo,Nagongera,Martin Donnelly,Craig Wilding,2012,S,F,101330674,32.73,ERS223956,0.77000,34.02600
AC0093-C,1_A10,UGgam,Uganda,Tororo,Nagongera,Martin Donnelly,Craig Wilding,2012,S,F,117315684,38.30,ERS223969,0.77000,34.02600
AV0001-C,KB001,GNgam,Guinea,Koraboh,Koraboh,Kenneth Vernick,"Michelle Riehle, Karin Eiglmeier",2012,S,F,101188184,32.05,ERS224851,9.25000,-9.91700
AV0002-C,KB002,GNgam,Guinea,Koraboh,Koraboh,Kenneth Vernick,"Michelle Riehle, Karin Eiglmeier",2012,S,F,84291044,28.08,ERS224584,9.25000,-9.91700
AV0003-C,KB003,GNgam,Guinea,Koraboh,Koraboh,Kenneth Vernick,"Michelle Riehle, Karin Eiglmeier",2012,S,F,93939098,29.99,ERS224640,9.25000,-9.91700
AV0004-C,KB008,GNgam,Guinea,Koraboh,Koraboh,Kenneth Vernick,"Michelle Riehle, Karin Eiglmeier",2012,S,F,125181816,40.42,ERS224852,9.25000,-9.91700
AV0005-C,KB010,GNgam,Guinea,Koraboh,Koraboh,Kenneth Vernick,"Michelle Riehle, Karin Eiglmeier",2012,S,F,106810266,35.11,ERS224617,9.25000,-9.91700

In [16]:
# save only index values
df_indices = pd.DataFrame(df_west_and_outgroup.index)
df_indices

     ox_code
0   AA0048-C
1   AA0050-C
2   AA0060-C
3   AA0061-C
4   AA0072-C
5   AB0085-C
6   AB0103-C
7   AB0104-C
8   AB0108-C
9   AB0117-C
10  AC0089-C
11  AC0090-C
12  AC0091-C
13  AC0092-C
14  AC0093-C
15  AV0001-C
16  AV0002-C
17  AV0003-C
18  AV0004-C
19  AV0005-C

In [17]:
# save selected Pandas dataframe to a file
outfilename = f"samples_west_and_outgroup.meta.{index_col}.txt"

print(f"Saving `df_indices` to {outfilename}")
df_indices.to_csv(outfilename, sep='\t', index=False, header=False)

Saving `df_indices` to samples_west_and_outgroup.meta.ox_code.txt

In [18]:
# display what is inside the saved file
df_outfile = pd.read_csv(outfilename, sep='\t', header=None)
df_outfile

           0
0   AA0048-C
1   AA0050-C
2   AA0060-C
3   AA0061-C
4   AA0072-C
5   AB0085-C
6   AB0103-C
7   AB0104-C
8   AB0108-C
9   AB0117-C
10  AC0089-C
11  AC0090-C
12  AC0091-C
13  AC0092-C
14  AC0093-C
15  AV0001-C
16  AV0002-C
17  AV0003-C
18  AV0004-C
19  AV0005-C

# Filter out in `VCFtools`

## Prerequisites

### `VCFtools`

Download and install `VCFtools` at https://vcftools.github.io/index.html

### Data

Download [ag1000g.phase2.ar1.pass.3L.vcf.gz](ftp://ngs.sanger.ac.uk/production/ag1000g/phase2/AR1/variation/main/vcf/pass/ag1000g.phase2.ar1.pass.3L.vcf.gz) (chromosome 3L) from [ftp://ngs.sanger.ac.uk/production/ag1000g/phase2/AR1/variation/main/vcf/pass/](ftp://ngs.sanger.ac.uk/production/ag1000g/phase2/AR1/variation/main/vcf/pass/)

## Individual filtering

From https://vcftools.github.io/man_latest.html#INDIVIDUAL%20FILTERING%20OPTIONS

> --keep <filename>
>    
> --remove <filename>
> 
> Provide files containing a list of individuals to either include or exclude in subsequent analysis. Each individual ID (as defined in the VCF headerline) should be included on a separate line. If both options are used, then the "--keep" option is executed before the "--remove" option. When multiple files are provided, the union of individuals from all keep files subtracted by the union of individuals from all remove files are kept. No header line is expected.

## Position filtering


From https://vcftools.github.io/man_latest.html#INDIVIDUAL%20FILTERING%20OPTIONS

> --from-bp <integer>
> --to-bp <integer>
>
> These options specify a lower bound and upper bound for a range of sites to be processed. Sites with positions less than or greater than these values will be excluded. These options can only be used in conjunction with a single usage of --chr. Using one of these does not require use of the other.

## Run filtering in `bash`

In [38]:
%%time
%%bash
# uncomment/comment out below to run/not run filtering
# vcftools --gzvcf ag1000g.phase2.ar1.pass.3L.vcf.gz --keep samples_west_and_outgroup.meta.ox_code.txt --chr 3L --from-bp 1000000 --to-bp 1999999 --recode --out ag1000g.phase2.ar1.pass.3L.west_and_outgroup

VCFtools - 0.1.17
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
	--gzvcf ag1000g.phase2.ar1.pass.3L.vcf.gz
	--chr 3L
	--to-bp 1999999
	--keep samples_west_and_outgroup.meta.ox_code.txt
	--out ag1000g.phase2.ar1.pass.3L.west_and_outgroup
	--recode
	--from-bp 1000000

Using zlib version: 1.2.11
Warning: Expected at least 2 parts in FORMAT entry: ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=RPA,Number=.,Type=Integer,Description="Number of times tandem repeat unit is repeated, for each allele (including reference)">
Keeping individuals in 'keep' list
After filtering, kept 20 out of 1142 Individuals
Outputting VCF file...
After filtering, kept 41869 out of a possible 10640388 Sites
Run Time = 2530.00 seconds

CPU times: user 96.3 ms, sys: 35.2 ms, total: 131 ms
Wall time: 42min 10s

Filtering 1,000,000 base-pair (1 Mbp) positions would take ~40 min:

```bash

VCFtools - 0.1.17
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
	--gzvcf ag1000g.phase2.ar1.pass.3L.vcf.gz
	--chr 3L
	--to-bp 1999999
	--keep samples_west_and_outgroup.meta.ox_code.txt
	--out ag1000g.phase2.ar1.pass.3L.west_and_outgroup
	--recode
	--from-bp 1000000

Using zlib version: 1.2.11
Warning: Expected at least 2 parts in FORMAT entry: ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=RPA,Number=.,Type=Integer,Description="Number of times tandem repeat unit is repeated, for each allele (including reference)">
Keeping individuals in 'keep' list
After filtering, kept 20 out of 1142 Individuals
Outputting VCF file...
After filtering, kept 41869 out of a possible 10640388 Sites
Run Time = 2530.00 seconds
CPU times: user 96.3 ms, sys: 35.2 ms, total: 131 ms
Wall time: 42min 10s
```

## Compare new and original `vcf` files

Display the head of the original `vcf` file:

In [11]:
%%bash
zcat ag1000g.phase2.ar1.pass.3L.vcf.gz | vcf-to-tab | head -n 5 >orig.tsv

In [12]:
pd.read_csv("orig.tsv", sep='\t')

,#CHROM,POS,REF,AA0040-C,AA0041-C,AA0042-C,AA0043-C,AA0044-C,AA0048-C,AA0049-C,...,AY0079-C,AY0080-C,AY0082-C,AY0083-C,AY0085-C,AY0087-C,AY0088-C,AY0089-C,AY0090-C,AY0091-C
0,3L,9790,C,C/C,C/C,C/C,C/C,C/C,C/C,C/C,...,C/C,C/C,C/C,C/C,C/C,C/C,C/C,C/C,C/C,C/C
1,3L,9791,G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,...,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G
2,3L,9798,G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,...,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G
3,3L,9812,C,C/C,C/C,C/C,C/C,C/C,C/C,C/C,...,C/C,C/C,C/C,C/C,C/C,C/C,C/C,C/C,C/C,C/C

In [13]:
%%bash
rm orig.tsv

Display the head of the new (recoded) `vcf` file:

In [14]:
%%bash
cat ag1000g.phase2.ar1.pass.3L.Ghana.recode.vcf | vcf-to-tab | head -n 5 >recoded.tsv

In [15]:
pd.read_csv("recoded.tsv", sep='\t')

,#CHROM,POS,REF,AA0040-C,AA0041-C,AA0042-C,AA0043-C,AA0044-C,AA0048-C,AA0049-C,...,AA0125-C,AA0127-C,AA0132-C,AA0133-C,AA0134-C,AA0135-C,AA0136-C,AA0139-C,AA0140-C,AA0141-C
0,3L,1002360,G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,...,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G
1,3L,1002365,A,A/A,A/A,A/A,A/A,A/A,A/A,A/A,...,A/A,A/A,A/A,A/A,A/A,A/A,A/A,A/A,A/A,A/A
2,3L,1002373,T,T/T,T/T,T/T,T/T,T/T,T/T,T/T,...,T/T,T/T,T/T,T/T,T/T,T/T,T/T,T/T,T/T,T/T
3,3L,1002379,G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,...,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G

In [16]:
%%bash
rm recoded.tsv

## Validate the recoded `vcf` file

Compress `vcf` file to `vcf.gz`:

In [17]:
%%bash
gzip -k ag1000g.phase2.ar1.pass.3L.Ghana.recode.vcf
ls -lh ag1000g.phase2.ar1.pass.3L.Ghana.recode.vcf*

-rw-rw-r-- 1 mathemage mathemage 83M dub 24 20:15 ag1000g.phase2.ar1.pass.3L.Ghana.recode.vcf
-rw-rw-r-- 1 mathemage mathemage 14M dub 24 20:15 ag1000g.phase2.ar1.pass.3L.Ghana.recode.vcf.gz

Validate the recoded file:

In [19]:
%%bash
vcf-validator -d ag1000g.phase2.ar1.pass.3L.Ghana.recode.vcf.gz