# Set Variables

Set variable below to the desired country for filtering:

In [1]:
country = "Ghana"

Set index column:

In [2]:
index_col = "ox_code"

# Get IDs of mosquitoes from a single country

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("samples.meta.txt", sep='\t', index_col=index_col)
df

,src_code,population,country,location,site,contributor,contact,year,m_s,sex,n_sequences,mean_coverage,ebi_sample_acc,latitude,longitude
ox_code,,,,,,,,,,,,,,,
AA0040-C,Twifo_Praso__E2,GHcol,Ghana,Twifo Praso,Twifo Praso,David Weetman,David Weetman,2012,M,F,95033368,30.99,ERS311878,5.60858,-1.54926
AA0041-C,Twifo_Praso__H3,GHcol,Ghana,Twifo Praso,Twifo Praso,David Weetman,David Weetman,2012,M,F,95843804,31.70,ERS311886,5.60858,-1.54926
AA0042-C,Takoradi_C7,GHcol,Ghana,Takoradi,Takoradi,David Weetman,David Weetman,2012,M,F,107420666,35.65,ERS311894,4.91217,-1.77397
AA0043-C,Takoradi_H8,GHcol,Ghana,Takoradi,Takoradi,David Weetman,David Weetman,2012,M,F,95993752,29.46,ERS311902,4.91217,-1.77397
AA0044-C,Takoradi_D10,GHcol,Ghana,Takoradi,Takoradi,David Weetman,David Weetman,2012,M,F,103044262,33.67,ERS311910,4.91217,-1.77397
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AY0087-C,Tia_dPM_46,CIcol,Cote d'Ivoire,Tiassale,Tiassale,David Weetman,David Weetman,2012,M,F,101458232,32.56,ERS311822,5.89839,-4.82293
AY0088-C,Tia_dPM_52,CIcol,Cote d'Ivoire,Tiassale,Tiassale,David Weetman,David Weetman,2012,M,F,95140584,30.75,ERS311830,5.89839,-4.82293
AY0089-C,Tia_aPM_4,CIcol,Cote d'Ivoire,Tiassale,Tiassale,David Weetman,David Weetman,2012,M,F,92383724,29.04,ERS311838,5.89839,-4.82293
AY0090-C,Tia_aPM_13,CIcol,Cote d'Ivoire,Tiassale,Tiassale,David Weetman,David Weetman,2012,M,F,96210618,30.94,ERS311846,5.89839,-4.82293
AY0091-C,Tia_aPM_37,CIcol,Cote d'Ivoire,Tiassale,Tiassale,David Weetman,David Weetman,2012,M,F,95973872,31.30,ERS311854,5.89839,-4.82293

In [11]:
countries = df["country"].unique()
countries

array(['Ghana', 'Burkina Faso', 'Uganda', 'Gambia, The', 'Guinea-Bissau',
       'Kenya', 'Cameroon', 'France', 'Equatorial Guinea', 'Angola',
       'Gabon', 'Guinea', "Cote d'Ivoire"], dtype=object)

From https://en.wikipedia.org/wiki/West_Africa \[accessed on May 1, 2020\]

> The United Nations defines Western Africa as the 16 countries of Benin, Burkina Faso, Cape Verde, The Gambia, Ghana, Guinea, Guinea-Bissau, Ivory Coast, Liberia, Mali, Mauritania, Niger, Nigeria, Senegal, Sierra Leone and Togo, as well as the United Kingdom Overseas Territory of Saint Helena, Ascension and Tristan da Cunha

In [ ]:
west_afr = None
outgroup = None

In [5]:
selection_mask = df["country"] == country
selection_mask

ox_code
AA0040-C     True
AA0041-C     True
AA0042-C     True
AA0043-C     True
AA0044-C     True
            ...
AY0087-C    False
AY0088-C    False
AY0089-C    False
AY0090-C    False
AY0091-C    False
Name: country, Length: 1142, dtype: bool

From https://vcftools.github.io/man_latest.html#INDIVIDUAL%20FILTERING%20OPTIONS

> --keep <filename>
>    
> --remove <filename>
> 
> Provide files containing a list of individuals to either include or exclude in subsequent analysis. Each individual ID (as defined in the VCF headerline) should be included on a separate line. If both options are used, then the "--keep" option is executed before the "--remove" option. When multiple files are provided, the union of individuals from all keep files subtracted by the union of individuals from all remove files are kept. No header line is expected.

In [6]:
df_single_country = df[selection_mask]
df_single_country

,src_code,population,country,location,site,contributor,contact,year,m_s,sex,n_sequences,mean_coverage,ebi_sample_acc,latitude,longitude
ox_code,,,,,,,,,,,,,,,
AA0040-C,Twifo_Praso__E2,GHcol,Ghana,Twifo Praso,Twifo Praso,David Weetman,David Weetman,2012,M,F,95033368,30.99,ERS311878,5.60858,-1.54926
AA0041-C,Twifo_Praso__H3,GHcol,Ghana,Twifo Praso,Twifo Praso,David Weetman,David Weetman,2012,M,F,95843804,31.70,ERS311886,5.60858,-1.54926
AA0042-C,Takoradi_C7,GHcol,Ghana,Takoradi,Takoradi,David Weetman,David Weetman,2012,M,F,107420666,35.65,ERS311894,4.91217,-1.77397
AA0043-C,Takoradi_H8,GHcol,Ghana,Takoradi,Takoradi,David Weetman,David Weetman,2012,M,F,95993752,29.46,ERS311902,4.91217,-1.77397
AA0044-C,Takoradi_D10,GHcol,Ghana,Takoradi,Takoradi,David Weetman,David Weetman,2012,M,F,103044262,33.67,ERS311910,4.91217,-1.77397
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AA0135-C,Twifo_Praso__C5,GHcol,Ghana,Twifo Praso,Twifo Praso,David Weetman,David Weetman,2012,M,F,105874060,34.37,ERS311966,5.60858,-1.54926
AA0136-C,Takoradi_A12,GHcol,Ghana,Takoradi,Takoradi,David Weetman,David Weetman,2012,M,F,100355038,31.34,ERS311967,4.91217,-1.77397
AA0139-C,Madina_F6,GHcol,Ghana,Madina,Madina,David Weetman,David Weetman,2012,M,F,97694602,31.65,ERS311970,5.66849,-0.21928
AA0140-C,Madina_G6,GHcol,Ghana,Madina,Madina,David Weetman,David Weetman,2012,M,F,97619200,31.97,ERS311971,5.66849,-0.21928
AA0141-C,Madina_H6,GHcol,Ghana,Madina,Madina,David Weetman,David Weetman,2012,M,F,107530492,34.83,ERS311972,5.66849,-0.21928

In [7]:
# save only index values
df_single_country_indices = pd.DataFrame(df_single_country.index)
df_single_country_indices

     ox_code
0   AA0040-C
1   AA0041-C
2   AA0042-C
3   AA0043-C
4   AA0044-C
..       ...
62  AA0135-C
63  AA0136-C
64  AA0139-C
65  AA0140-C
66  AA0141-C

[67 rows x 1 columns]

In [8]:
# save selected Pandas dataframe to a file
outfilename = f"samples_{country}.meta.{index_col}.txt"

print(f"Saving `df_single_country_indices` to {outfilename}")
df_single_country_indices.to_csv(outfilename, sep='\t', index=False, header=False)

Saving `df_single_country_indices` to samples_Ghana.meta.ox_code.txt

In [9]:
# display what is inside the saved file
df_outfile = pd.read_csv(outfilename, sep='\t', header=None)
df_outfile

           0
0   AA0040-C
1   AA0041-C
2   AA0042-C
3   AA0043-C
4   AA0044-C
..       ...
62  AA0135-C
63  AA0136-C
64  AA0139-C
65  AA0140-C
66  AA0141-C

[67 rows x 1 columns]

# Filter out in `VCFtools`

## Prerequisites

### `VCFtools`

Download and install `VCFtools` at https://vcftools.github.io/index.html

### Data

Download [ag1000g.phase2.ar1.pass.3L.vcf.gz](ftp://ngs.sanger.ac.uk/production/ag1000g/phase2/AR1/variation/main/vcf/pass/ag1000g.phase2.ar1.pass.3L.vcf.gz) (chromosome 3L) from [ftp://ngs.sanger.ac.uk/production/ag1000g/phase2/AR1/variation/main/vcf/pass/](ftp://ngs.sanger.ac.uk/production/ag1000g/phase2/AR1/variation/main/vcf/pass/)

## Position filtering


From https://vcftools.github.io/man_latest.html#INDIVIDUAL%20FILTERING%20OPTIONS

> --from-bp <integer>
> --to-bp <integer>
>
> These options specify a lower bound and upper bound for a range of sites to be processed. Sites with positions less than or greater than these values will be excluded. These options can only be used in conjunction with a single usage of --chr. Using one of these does not require use of the other.

## Run filtering in `bash`

In [10]:
# uncomment/comment out below to run/not run filtering
#!vcftools --gzvcf ag1000g.phase2.ar1.pass.3L.vcf.gz --keep samples_Ghana.meta.ox_code.txt --chr 3L --from-bp 1000000 --to-bp 1999999 --recode --out ag1000g.phase2.ar1.pass.3L.Ghana

Filtering 10 base-pair (bp) positions would take ~40 min:

```bash
time vcftools --gzvcf ag1000g.phase2.ar1.pass.3L.vcf.gz --keep samples_Ghana.meta.ox_code.txt --chr 3L --from-bp 1000010 --to-bp 1000019 --recode --out ag1000g.phase2.ar1.pass.3L.Ghana

VCFtools - 0.1.17
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
        --gzvcf ag1000g.phase2.ar1.pass.3L.vcf.gz
        --chr 3L
        --to-bp 1000019
        --keep samples_Ghana.meta.ox_code.txt
        --out ag1000g.phase2.ar1.pass.3L.Ghana
        --recode
        --from-bp 1000010

Using zlib version: 1.2.11
Warning: Expected at least 2 parts in FORMAT entry: ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=RPA,Number=.,Type=Integer,Description="Number of times tandem repeat unit is repeated, for each allele (including reference)">
Keeping individuals in 'keep' list
After filtering, kept 67 out of 1142 Individuals
Outputting VCF file...
After filtering, kept 0 out of a possible 10640388 Sites
No data left for analysis!
Run Time = 2357.00 seconds

real    39m17,515s
user    34m20,231s
sys     0m41,935s
```

Filtering 1,000,000 base-pair (1 Mbp) positions would take ~90 min:

```bash

VCFtools - 0.1.17
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
	--gzvcf ag1000g.phase2.ar1.pass.3L.vcf.gz
	--chr 3L
	--to-bp 1999999
	--keep samples_Ghana.meta.ox_code.txt
	--out ag1000g.phase2.ar1.pass.3L.Ghana
	--recode
	--from-bp 1000000

Using zlib version: 1.2.11
Warning: Expected at least 2 parts in FORMAT entry: ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
Warning: Expected at least 2 parts in INFO entry: ID=RPA,Number=.,Type=Integer,Description="Number of times tandem repeat unit is repeated, for each allele (including reference)">
Keeping individuals in 'keep' list
After filtering, kept 67 out of 1142 Individuals
Outputting VCF file...
After filtering, kept 41869 out of a possible 10640388 Sites
Run Time = 5450.00 seconds
```

## Compare new and original `vcf` files

Display the head of the original `vcf` file:

In [11]:
%%bash
zcat ag1000g.phase2.ar1.pass.3L.vcf.gz | vcf-to-tab | head -n 5 >orig.tsv

In [12]:
pd.read_csv("orig.tsv", sep='\t')

,#CHROM,POS,REF,AA0040-C,AA0041-C,AA0042-C,AA0043-C,AA0044-C,AA0048-C,AA0049-C,...,AY0079-C,AY0080-C,AY0082-C,AY0083-C,AY0085-C,AY0087-C,AY0088-C,AY0089-C,AY0090-C,AY0091-C
0,3L,9790,C,C/C,C/C,C/C,C/C,C/C,C/C,C/C,...,C/C,C/C,C/C,C/C,C/C,C/C,C/C,C/C,C/C,C/C
1,3L,9791,G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,...,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G
2,3L,9798,G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,...,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G
3,3L,9812,C,C/C,C/C,C/C,C/C,C/C,C/C,C/C,...,C/C,C/C,C/C,C/C,C/C,C/C,C/C,C/C,C/C,C/C

In [13]:
%%bash
rm orig.tsv

Display the head of the new (recoded) `vcf` file:

In [14]:
%%bash
cat ag1000g.phase2.ar1.pass.3L.Ghana.recode.vcf | vcf-to-tab | head -n 5 >recoded.tsv

In [15]:
pd.read_csv("recoded.tsv", sep='\t')

,#CHROM,POS,REF,AA0040-C,AA0041-C,AA0042-C,AA0043-C,AA0044-C,AA0048-C,AA0049-C,...,AA0125-C,AA0127-C,AA0132-C,AA0133-C,AA0134-C,AA0135-C,AA0136-C,AA0139-C,AA0140-C,AA0141-C
0,3L,1002360,G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,...,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G
1,3L,1002365,A,A/A,A/A,A/A,A/A,A/A,A/A,A/A,...,A/A,A/A,A/A,A/A,A/A,A/A,A/A,A/A,A/A,A/A
2,3L,1002373,T,T/T,T/T,T/T,T/T,T/T,T/T,T/T,...,T/T,T/T,T/T,T/T,T/T,T/T,T/T,T/T,T/T,T/T
3,3L,1002379,G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,...,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G,G/G

In [16]:
%%bash
rm recoded.tsv

## Validate the recoded `vcf` file

Compress `vcf` file to `vcf.gz`:

In [17]:
%%bash
gzip -k ag1000g.phase2.ar1.pass.3L.Ghana.recode.vcf
ls -lh ag1000g.phase2.ar1.pass.3L.Ghana.recode.vcf*

-rw-rw-r-- 1 mathemage mathemage 83M dub 24 20:15 ag1000g.phase2.ar1.pass.3L.Ghana.recode.vcf
-rw-rw-r-- 1 mathemage mathemage 14M dub 24 20:15 ag1000g.phase2.ar1.pass.3L.Ghana.recode.vcf.gz

Validate the recoded file:

In [19]:
%%bash
vcf-validator -d ag1000g.phase2.ar1.pass.3L.Ghana.recode.vcf.gz